# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='list_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='todo.List'),
        ),
    ]
