# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20160929_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exp_date',
            field=models.DateField(default=None),
        ),
    ]
